# Version: 1.0.1
# Last modified: 2025-10-24 17:33 by CNC-Buddy
from typing import List

from homeassistant.components.sensor import SensorDeviceClass
from homeassistant.helpers.entity import EntityCategory
from homeassistant.util import slugify

# Bit label mappings for bitfield registers (from main.xlsx), English labels
RUNNING_STATUS_1_BITS = {
    0: "Refrigerator recycling",
    1: "First level anti-freezing",
    2: "Second level anti-freezing",
    3: "Failure warning",
    4: "System 1 return oil",
    8: "System defrost",
    12: "Constant temperature shutdown",
    13: "Fault shutdown protection",
    14: "Machine run",
    15: "Machine wait to run",
}

RUNNING_STATUS_2_BITS = {
    0: "High temperature Sterilization",
    1: "High temperature Sterilization Heat Preservation",
    10: "Controller on / off",
}

FAULT_STATE_1_BITS = {
    0: "Wrong phase fault",
    1: "Lack of phase fault",
    2: "Water flow fault",
    3: "Communication fault",
    4: "Emergency fault",
    5: "Use time expired",
    6: "Water tank (down) temperature fault",
    7: "Water inlet temperature fault",
    8: "Indoor temperature fault",
    9: "Environmental temperature fault",
    10: "User backwater temperature fault",
    11: "Cooling outlet water level is too low",
    12: "Water level switch fault",
    13: "Water outlet temperature fault",
    14: "Heating outlet water level is too high",
    15: "Excessive inlet/outlet water temperature difference",
}

FAULT_STATE_2_BITS = {
    0: "Environmental low temperature protection",
    11: "Phase order dial error",
    13: "Water pump 1 feedback fault",
    14: "Water pump 2 feedback fault",
    15: "Low water flow protection",
}

FAULT_STATE_3_BITS = {
    0: "Phase sequence disconnected",
    1: "Expansion board communication",
    2: "Plate Heat Exchanger temperature fault",
    3: "Fan motor 1 communication fault",
    4: "Fan motor 2 communication fault",
    5: "Online model not matching error",
    6: "Aux HW Sensor Error",
    7: "Aux Heating Sensor Error",
    8: "Buffer Tank Error",
    9: "Main Water Outlet Temperature Error",
}

SYS_FAULT_STATE_1_BITS = {
    0: "High pressure switch protection",
    1: "Low pressure switch protection",
    2: "High pressure over high protection",
    3: "Low pressure over low protection",
    4: "Exhaust over protection",
    5: "Current protection",
    6: "Coil Temperature over protection",
    7: "Coil temperature fault",
    8: "Return air temperature fault",
    9: "Exhaust temperature fault",
    10: "Economizer Inlet temperature fault",
    11: "Economizer Outlet temperature fault",
    12: "Fan drive communication fault",
    13: "DC fan fault",
    14: "Refrigeration coil temperature fault",
}

SYS_FAULT_STATE_2_BITS = {
    0: "High pressure sensor fault",
    1: "Low pressure sensor fault",
    2: "Middle Pressure switch fault",
    3: "Coil Temperature over high",
    4: "Compressor Drive Board communication fault",
}

SYS_DRIVE_FAULT_STATE_1_BITS = {
    0: "IPM overcurrent/IPM module protection",
    1: "Compressor drive fault",
    2: "Compressor overcurrent",
    3: "Input voltage phase loss",
    4: "IPM current sampling fault",
    5: "Overheating shutdown of power components",
    6: "Precharge failed",
    7: "DC bus overvoltage",
    8: "DC bus undervoltage",
    9: "AC input undervoltage",
    10: "AC input overcurrent",
    11: "Input voltage sampling fault",
}

SYS_DRIVE_FAULT_STATE_2_BITS = {
    0: "Compressor overcurrent alarm",
    1: "Compressor field weakening protection alarm",
    2: "PIM overheat alarm",
    3: "PFC overheat alarm",
    4: "AC input overcurrent alarm",
    5: "EEPROM fault alarm",
    7: "EEPROM refresh completed",
    8: "Temperature sensing fault frequency limit",
    9: "AC undervoltage frequency limit protection alarm",
}
SYS_DRIVE_FAULT_STATE_3_BITS = {
    0: "IPM module thermal shutdown",
    1: "Compressor phase loss",
    2: "Compressor overload",
    3: "Input current sampling fault",
    4: "PIM supply voltage fault",
    5: "Precharge circuit voltage fault",
    6: "EEPROM fault",
    7: "AC input overvoltage fault",
    8: "Microelectronics fault",
    9: "Compressor model code fault",
    10: "Current sampling signal overcurrent",
}

# Relay output status bit labels
RELAY_OUTPUT_STATUS_1_BITS = {
    0: "Hot water electric heating",
    1: "Fan high wind",
    3: "Fan low wind",
    4: "Air conditioner electric heating",
    5: "Floor heating electric heating",
    6: "Main engine circulating water pump",
    9: "Electric crankshaft heating",
    10: "Chassis electric heating",
    11: "Return valve/pump",
    14: "Air conditioner solenoid valve / three-way valve",
    15: "Floor heating solenoid valve / three-way valve",
}
RELAY_OUTPUT_STATUS_2_BITS = {
    0: "Compressor 1",
    1: "Liquid injection solenoid valve 1",
    2: "Enthalpy solenoid valve 1",
    3: "Four-way valve 1",
    4: "Throttle bypass valve 1",
    5: "Fan motor 1",
    8: "Auxiliary Heating Pump",
    10: "Compressor 2",
    11: "Spray solenoid valve 2",
    12: "Enthalpy increasing solenoid valve 2",
    13: "Four-way valve 2",
}
RELAY_OUTPUT_STATUS_3_BITS = {
    6: "Expansion Tank Heating Element",
    7: "Auxiliary Heat Source Hot water Pump",
    8: "Auxiliary Heat Source Heating Pump",
    9: "Gas Output",
}
RELAY_OUTPUT_STATUS_4_BITS = {
    0: "Pipeline electric heating 1",
    1: "Pipeline electric heating 2",
}

# Switch port state bit labels
SWITCH_PORT_STATE_1_BITS = {
    0: "SW1",
    1: "SW2",
    2: "SW3",
    3: "SW4",
    4: "SW5",
    5: "SW6",
    6: "SW7",
    7: "SW8",
    8: "Water Flow Switch",
    10: "House Heating Linkage Switch",
    11: "Auxiliary Hot Water Linkage Switch",
    12: "Linkage switch",
    13: "Emergency switch",
}
SWITCH_PORT_STATE_2_BITS = {
    7: "High Pressure 1 Switch",
    8: "Low Pressure 1 switch",
    9: "Medium Pressure 1 switch",
    10: "High Pressure 2 Switch",
    11: "Low Pressure 2 switch",
    12: "Medium Pressure 2 switch",
}
SWITCH_PORT_STATE_3_BITS = {
    5: "Auxiliary Heating Linkage Switch",
}
SWITCH_PORT_STATE_4_BITS = {
}

MAIN_SENSORS = [
    {
        "name": "Running Status 1",
        "unique_id": "r290_heatpump_running_status_1",
        "address": 0x0000,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": "",
        "device_class": None,
        "state_class": "measurement",
        "precision": 0,
        "bit_labels": RUNNING_STATUS_1_BITS,
    },
    {
        "name": "Running Status 2",
        "unique_id": "r290_heatpump_running_status_2",
        "address": 0x0001,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": "",
        "device_class": None,
        "state_class": "measurement",
        "precision": 0,
        "bit_labels": RUNNING_STATUS_2_BITS,
    },
    {
        "name": "Fault State 1",
        "unique_id": "r290_heatpump_fault_state_1",
        "address": 0x0002,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": "",
        "device_class": None,
        "state_class": "measurement",
        "precision": 0,
        "bit_labels": FAULT_STATE_1_BITS,
    },
    {
        "name": "Fault State 2",
        "unique_id": "r290_heatpump_fault_state_2",
        "address": 0x0003,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": "",
        "device_class": None,
        "state_class": "measurement",
        "precision": 0,
        "bit_labels": FAULT_STATE_2_BITS,
    },
    {
        "name": "Fault State 3",
        "unique_id": "r290_heatpump_fault_state_3",
        "address": 0x0004,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": "",
        "device_class": None,
        "state_class": "measurement",
        "precision": 0,
        "bit_labels": FAULT_STATE_3_BITS,
    },
    {
        "name": "System 1 Fault State 1",
        "unique_id": "r290_heatpump_system_1_fault_state_1",
        "address": 0x0005,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": "",
        "device_class": None,
        "state_class": "measurement",
        "precision": 0,
        "bit_labels": SYS_FAULT_STATE_1_BITS,
    },
    {
        "name": "System 1 Fault State 2",
        "unique_id": "r290_heatpump_system_1_fault_state_2",
        "address": 0x0006,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": "",
        "device_class": None,
        "state_class": "measurement",
        "precision": 0,
        "bit_labels": SYS_FAULT_STATE_2_BITS,
    },
    {
        "name": "System 1 Drive Fault State 1",
        "unique_id": "r290_heatpump_system_1_drive_fault_state_1",
        "address": 0x0007,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": "",
        "device_class": None,
        "state_class": "measurement",
        "precision": 0,
        "bit_labels": SYS_DRIVE_FAULT_STATE_1_BITS,
    },
    {
        "name": "System 1 Drive Fault State 2",
        "unique_id": "r290_heatpump_system_1_drive_fault_state_2",
        "address": 0x0008,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": "",
        "device_class": None,
        "state_class": "measurement",
        "precision": 0,
        "bit_labels": SYS_DRIVE_FAULT_STATE_2_BITS,
    },
    {
        "name": "System 1 Drive Fault State 3",
        "unique_id": "r290_heatpump_system_1_drive_fault_state_3",
        "address": 0x0009,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": "",
        "device_class": None,
        "state_class": "measurement",
        "precision": 0,
        "bit_labels": SYS_DRIVE_FAULT_STATE_3_BITS,
    },
    {
        "name": "System 2 Fault State 1",
        "unique_id": "r290_heatpump_system_2_fault_state_1",
        "address": 0x000A,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": "",
        "device_class": None,
        "state_class": "measurement",
        "precision": 0,
        "bit_labels": SYS_FAULT_STATE_1_BITS,
    },
    {
        "name": "System 2 Fault State 2",
        "unique_id": "r290_heatpump_system_2_fault_state_2",
        "address": 0x000B,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": "",
        "device_class": None,
        "state_class": "measurement",
        "precision": 0,
        "bit_labels": SYS_FAULT_STATE_2_BITS,
    },
    {
        "name": "System 2 Drive Fault State 1",
        "unique_id": "r290_heatpump_system_2_drive_fault_state_1",
        "address": 0x000C,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": "",
        "device_class": None,
        "state_class": "measurement",
        "precision": 0,
        "bit_labels": SYS_DRIVE_FAULT_STATE_1_BITS,
    },
    {
        "name": "System 2 Drive Fault State 2",
        "unique_id": "r290_heatpump_system_2_drive_fault_state_2",
        "address": 0x000D,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": "",
        "device_class": None,
        "state_class": "measurement",
        "precision": 0,
        "bit_labels": SYS_DRIVE_FAULT_STATE_2_BITS,
    },
    {
        "name": "System 2 Drive Fault State 3",
        "unique_id": "r290_heatpump_system_2_drive_fault_state_3",
        "address": 0x000E,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": "",
        "device_class": None,
        "state_class": "measurement",
        "precision": 0,
        "bit_labels": SYS_DRIVE_FAULT_STATE_3_BITS,
    },
    # System 3 (disabled by default)
    {
        "name": "System 3 Fault State 1",
        "unique_id": "r290_heatpump_system_3_fault_state_1",
        "address": 0x000F,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": "",
        "device_class": None,
        "state_class": "measurement",
        "precision": 0,
        "bit_labels": SYS_FAULT_STATE_1_BITS,
        "enabled_by_default": False,
    },
    {
        "name": "System 3 Fault State 2",
        "unique_id": "r290_heatpump_system_3_fault_state_2",
        "address": 0x0010,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": "",
        "device_class": None,
        "state_class": "measurement",
        "precision": 0,
        "bit_labels": SYS_FAULT_STATE_2_BITS,
        "enabled_by_default": False,
    },
    {
        "name": "System 3 Drive Fault State 1",
        "unique_id": "r290_heatpump_system_3_drive_fault_state_1",
        "address": 0x0011,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": "",
        "device_class": None,
        "state_class": "measurement",
        "precision": 0,
        "bit_labels": SYS_DRIVE_FAULT_STATE_1_BITS,
        "enabled_by_default": False,
    },
    {
        "name": "System 3 Drive Fault State 2",
        "unique_id": "r290_heatpump_system_3_drive_fault_state_2",
        "address": 0x0012,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": "",
        "device_class": None,
        "state_class": "measurement",
        "precision": 0,
        "bit_labels": SYS_DRIVE_FAULT_STATE_2_BITS,
        "enabled_by_default": False,
    },
    {
        "name": "System 3 Drive Fault State 3",
        "unique_id": "r290_heatpump_system_3_drive_fault_state_3",
        "address": 0x0013,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": "",
        "device_class": None,
        "state_class": "measurement",
        "precision": 0,
        "bit_labels": SYS_DRIVE_FAULT_STATE_3_BITS,
        "enabled_by_default": False,
    },
    # System 4 (disabled by default)
    {
        "name": "System 4 Fault State 1",
        "unique_id": "r290_heatpump_system_4_fault_state_1",
        "address": 0x0014,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": "",
        "device_class": None,
        "state_class": "measurement",
        "precision": 0,
        "bit_labels": SYS_FAULT_STATE_1_BITS,
        "enabled_by_default": False,
    },
    {
        "name": "System 4 Fault State 2",
        "unique_id": "r290_heatpump_system_4_fault_state_2",
        "address": 0x0015,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": "",
        "device_class": None,
        "state_class": "measurement",
        "precision": 0,
        "bit_labels": SYS_FAULT_STATE_2_BITS,
        "enabled_by_default": False,
    },
    {
        "name": "System 4 Drive Fault State 1",
        "unique_id": "r290_heatpump_system_4_drive_fault_state_1",
        "address": 0x0016,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": "",
        "device_class": None,
        "state_class": "measurement",
        "precision": 0,
        "bit_labels": SYS_DRIVE_FAULT_STATE_1_BITS,
        "enabled_by_default": False,
    },
    {
        "name": "System 4 Drive Fault State 2",
        "unique_id": "r290_heatpump_system_4_drive_fault_state_2",
        "address": 0x0017,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": "",
        "device_class": None,
        "state_class": "measurement",
        "precision": 0,
        "bit_labels": SYS_DRIVE_FAULT_STATE_2_BITS,
        "enabled_by_default": False,
    },
    {
        "name": "System 4 Drive Fault State 3",
        "unique_id": "r290_heatpump_system_4_drive_fault_state_3",
        "address": 0x0018,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": "",
        "device_class": None,
        "state_class": "measurement",
        "precision": 0,
        "bit_labels": SYS_DRIVE_FAULT_STATE_3_BITS,
        "enabled_by_default": False,
    },
        {
        "name": "Relay output status 1",
        "unique_id": "r290_heatpump_relay_output_status_1",
        "address": 0x0019,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": "",
        "device_class": None,
        "state_class": "measurement",
        "precision": 0,
        "bit_labels": RELAY_OUTPUT_STATUS_1_BITS,
    },
    {
        "name": "Relay output status 2",
        "unique_id": "r290_heatpump_relay_output_status_2",
        "address": 0x001A,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": "",
        "device_class": None,
        "state_class": "measurement",
        "precision": 0,
        "bitfield": True,
        "bit_labels": RELAY_OUTPUT_STATUS_2_BITS,
    },
    {
        "name": "Relay output status 3",
        "unique_id": "r290_heatpump_relay_output_status_3",
        "address": 0x001B,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": "",
        "device_class": None,
        "state_class": "measurement",
        "precision": 0,
        "bitfield": True,
        "bit_labels": RELAY_OUTPUT_STATUS_3_BITS,
    },
    {
        "name": "Relay output status 4",
        "unique_id": "r290_heatpump_relay_output_status_4",
        "address": 0x001C,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": "",
        "device_class": None,
        "state_class": "measurement",
        "precision": 0,
        "bitfield": True,
        "bit_labels": RELAY_OUTPUT_STATUS_4_BITS,
    },
    {
        "name": "Switch Port State 1",
        "unique_id": "r290_heatpump_switch_port_state_1",
        "address": 0x001D,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": "",
        "device_class": None,
        "state_class": "measurement",
        "precision": 0,
        "bitfield": True,
        "bit_labels": SWITCH_PORT_STATE_1_BITS,
    },
    {
        "name": "Switch Port State 2",
        "unique_id": "r290_heatpump_switch_port_state_2",
        "address": 0x001E,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": "",
        "device_class": None,
        "state_class": "measurement",
        "precision": 0,
        "bitfield": True,
        "bit_labels": SWITCH_PORT_STATE_2_BITS,
    },
    {
        "name": "Switch Port State 3",
        "unique_id": "r290_heatpump_switch_port_state_3",
        "address": 0x001F,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": "",
        "device_class": None,
        "state_class": "measurement",
        "precision": 0,
        "bitfield": True,
        "bit_labels": SWITCH_PORT_STATE_3_BITS,
    },
    {
        "name": "Switch Port State 4",
        "unique_id": "r290_heatpump_switch_port_state_4",
        "address": 0x0020,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": "",
        "device_class": None,
        "state_class": "measurement",
        "precision": 0,
    "bitfield": True,
    },
    {
        "name": "Current unit tooling No",
        "unique_id": "r290_heatpump_current_unit_tooling_no",
        "address": 0x0024,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": "",
        "device_class": None,
        "state_class": "measurement",
        "precision": 0,

    },
    {
        "name": "Compressor 1 Target frequency",
        "unique_id": "r290_heatpump_compressor_1_target_frequency",
        "address": 0x0027,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": "Hz",
        "device_class": None,
        "state_class": "measurement",
        "precision": 0,
    },
    {
        "name": "Compressor 2 Target frequency",
        "unique_id": "r290_heatpump_compressor_2_target_frequency",
        "address": 0x0028,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": "Hz",
        "device_class": None,
        "state_class": "measurement",
        "precision": 0,
    },
]

BITFIELD_DIAGNOSTIC_SENSORS: List[dict] = []
for _base_sensor in list(MAIN_SENSORS):
    _bit_labels = _base_sensor.get("bit_labels")
    if not _bit_labels:
        continue

    _base_name = _base_sensor["name"]
    _base_slug = slugify(_base_name)
    _input_type = _base_sensor.get("input_type", "holding")
    _data_type = _base_sensor.get("data_type", "int16")

    for _bit_index, _bit_label in _bit_labels.items():
        if not _bit_label:
            continue

        _label_slug = slugify(str(_bit_label))
        _diag_slug = f"{_base_slug}_{_label_slug}_status"
        enabled_by_default = _diag_slug == "relay_output_status_2_compressor_1_status"
        BITFIELD_DIAGNOSTIC_SENSORS.append(
            {
                "name": f"{_base_name} {_bit_label} status",
                "unique_id": f"r290_heatpump_{_diag_slug}",
                "address": _base_sensor["address"],
                "input_type": _input_type,
                "data_type": _data_type,
                "scale": 1,
                "unit": None,
                "device_class": None,
                "state_class": None,
                "precision": 0,
                "bit": _bit_index,
                "entity_category": EntityCategory.DIAGNOSTIC,
                "enabled_by_default": enabled_by_default,
            }
        )

MAIN_SENSORS.extend(BITFIELD_DIAGNOSTIC_SENSORS)


COMPRESSOR_DIAGNOSTIC_COUNTERS = [
    {
        "status_slug": "relay_output_status_2_compressor_1_status",
        "start_name": "Compressor 1 Starts",
        "start_unique_id": "r290_heatpump_compressor_1_starts",
        "runtime_name": "Compressor 1 Runtime",
        "runtime_unique_id": "r290_heatpump_compressor_1_runtime",
    }
]













