# Version: 1.0.1
# Last modified: 2025-10-24 17:33 by CNC-Buddy
from homeassistant.components.sensor import SensorDeviceClass
from homeassistant.const import UnitOfElectricPotential, UnitOfTemperature

REALTIMEDATA_SENSORS = [
    {
        "name": "Compressor operating frequency",
        "unique_id": "r290_heatpump_compressor_operating_frequency",
        "address": 0x0040,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": "Hz",
        "device_class": SensorDeviceClass.FREQUENCY,
        "state_class": "measurement",
        "precision": 1,
    },
    {
        "name": "Fan operating frequency / rotational speed",
        "unique_id": "r290_heatpump_fan_operating_frequency_rotational_speed",
        "address": 0x0041,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": "RPM",
        "device_class": SensorDeviceClass.FREQUENCY,
        "state_class": "measurement",
        "precision": 1,
    },
    {
        "name": "Electronic expansion valve steps count",
        "unique_id": "r290_heatpump_electronic_expansion_valve_steps_count",
        "address": 0x0042,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": "",
        "device_class": SensorDeviceClass.POWER,
        "state_class": "measurement",
        "precision": 0,
    },
    {
        "name": "Number of EVI valve steps",
        "unique_id": "r290_heatpump_number_of_evi_valve_steps",
        "address": 0x0043,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": "",
        "device_class": SensorDeviceClass.POWER,
        "state_class": "measurement",
        "precision": 0,
        "enabled_by_default": False,
    },
    {
        "name": "AC Input Voltage",
        "unique_id": "r290_heatpump_ac_input_voltage",
        "address": 0x0044,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": UnitOfElectricPotential.VOLT,
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": "measurement",
        "precision": 1,
    },
    {
        "name": "AC Input Current",
        "unique_id": "r290_heatpump_ac_input_current",
        "address": 0x0045,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 0.1,
        "unit": "A",
        "device_class": SensorDeviceClass.CURRENT,
        "state_class": "measurement",
        "precision": 1,
        "enabled_by_default": False,
    },
    {
        "name": "Compressor Phase Current",
        "unique_id": "r290_heatpump_compressor_phase_current",
        "address": 0x0046,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 0.1,
        "unit": "A",
        "device_class": SensorDeviceClass.CURRENT,
        "state_class": "measurement",
        "precision": 1,
    },
    {
        "name": "Compressor IPM Temperature",
        "unique_id": "r290_heatpump_compressor_ipm_temperature",
        "address": 0x0047,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": UnitOfTemperature.CELSIUS,
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": "measurement",
        "precision": 1,
    },
    {
        "name": "High pressure saturation temperature",
        "unique_id": "r290_heatpump_high_pressure_saturation_temperature",
        "address": 0x0048,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": UnitOfTemperature.CELSIUS,
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": "measurement",
        "precision": 1,
    },
    {
        "name": "Low pressure saturation temperature",
        "unique_id": "r290_heatpump_low_pressure_saturation_temperature",
        "address": 0x0049,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": UnitOfTemperature.CELSIUS,
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": "measurement",
        "precision": 1,
    },
    {
        "name": "External ambient temperature T1",
        "unique_id": "r290_heatpump_external_ambient_temperature_t1",
        "address": 0x004A,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": UnitOfTemperature.CELSIUS,
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": "measurement",
        "precision": 1,
    },
    {
        "name": "External coil tube (fin) T2",
        "unique_id": "r290_heatpump_external_coil_tube_fin_t2",
        "address": 0x004B,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": UnitOfTemperature.CELSIUS,
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": "measurement",
        "precision": 1,
    },
    {
        "name": "Internal coil tube (plate replacement) T3",
        "unique_id": "r290_heatpump_internal_coil_tube_plate_replacement_t3",
        "address": 0x004C,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": UnitOfTemperature.CELSIUS,
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": "measurement",
        "precision": 1,
    },
    {
        "name": "Return air temperature T4",
        "unique_id": "r290_heatpump_return_air_temperature_t4",
        "address": 0x004D,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": UnitOfTemperature.CELSIUS,
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": "measurement",
        "precision": 1,
    },
    {
        "name": "Exhaust temperature T5",
        "unique_id": "r290_heatpump_exhaust_temperature_t5",
        "address": 0x004E,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": UnitOfTemperature.CELSIUS,
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": "measurement",
        "precision": 1,
    },
    {
        "name": "Return water temperature T6",
        "unique_id": "r290_heatpump_return_water_temperature_t6",
        "address": 0x004F,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": UnitOfTemperature.CELSIUS,
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": "measurement",
        "precision": 1,
    },
    {
        "name": "Water outlet temperature T7",
        "unique_id": "r290_heatpump_water_outlet_temperature_t7",
        "address": 0x0050,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": UnitOfTemperature.CELSIUS,
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": "measurement",
        "precision": 1,
    },
    {
        "name": "Economizer inlet tube T8",
        "unique_id": "r290_heatpump_economizer_inlet_tube_t8",
        "address": 0x0051,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": UnitOfTemperature.CELSIUS,
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": "measurement",
        "precision": 1,
        "enabled_by_default": False,
    },
    {
        "name": "Economizer outlet tube T9",
        "unique_id": "r290_heatpump_economizer_outlet_tube_t9",
        "address": 0x0052,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": UnitOfTemperature.CELSIUS,
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": "measurement",
        "precision": 1,
        "enabled_by_default": False,
    },
    {
        "name": "Current device tooling No.",
        "unique_id": "r290_heatpump_current_device_tooling_no",
        "address": 0x0053,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": "",
        "device_class": SensorDeviceClass.POWER,
        "state_class": "measurement",
        "precision": 0,
    },
    {
        "name": "Water tank temperature",
        "unique_id": "r290_heatpump_water_tank_temperature",
        "address": 0x0054,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": UnitOfTemperature.CELSIUS,
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": "measurement",
        "precision": 1,
    },
    {
        "name": "Fluorine outlet temperature of Plate Heat exchanger",
        "unique_id": "r290_heatpump_fluorine_outlet_temperature_of_plate_heat_exchanger",
        "address": 0x0055,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": UnitOfTemperature.CELSIUS,
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": "measurement",
        "precision": 1,
    },
    {
        "name": "Drive manufacturer",
        "unique_id": "r290_heatpump_drive_manufacturer",
        "address": 0x0056,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": "",
        "device_class": SensorDeviceClass.POWER,
        "state_class": "measurement",
        "precision": 0,
        "enabled_by_default": False,
    },
    {
        "name": "Pump speed PWM",
        "unique_id": "r290_heatpump_pump_speed_pwm",
        "address": 0x0057,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": "",
        "device_class": SensorDeviceClass.POWER,
        "state_class": "measurement",
        "precision": 0,
    },
    {
        "name": "Water flow",
        "unique_id": "r290_heatpump_water_flow",
        "address": 0x0058,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": "l/min",
        "device_class": None,
        "state_class": "measurement",
        "precision": 1,
    },
    {
        "name": "User return water temperature",
        "unique_id": "r290_heatpump_user_return_water_temperature",
        "address": 0x0059,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": UnitOfTemperature.CELSIUS,
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": "measurement",
        "precision": 1,
        "enabled_by_default": False,
    },
    {
        "name": "Device input voltage",
        "unique_id": "r290_heatpump_device_input_voltage",
        "address": 0x005A,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": "V",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": "measurement",
        "precision": 1,
        "enabled_by_default": False,
    },
    {
        "name": "Device input current",
        "unique_id": "r290_heatpump_device_input_current",
        "address": 0x005B,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 0.01,
        "unit": "A",
        "device_class": SensorDeviceClass.CURRENT,
        "state_class": "measurement",
        "precision": 1,
        "enabled_by_default": False,
    },
    {
        "name": "Device input power/kw",
        "unique_id": "r290_heatpump_device_input_power_kw",
        "address": 0x005C,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 0.01,
        "unit": "kw",
        "device_class": SensorDeviceClass.POWER,
        "state_class": "measurement",
        "precision": 1,
        "enabled_by_default": False,
    },
    {
        "name": "Total unit electricity consumption/kwh",
        "unique_id": "r290_heatpump_total_unit_electricity_consumption_kwh",
        "address": 0x005D,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": "kwh",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": "measurement",
        "precision": 1,
        "enabled_by_default": False,
    },
        {
        "name": "Auxiliary Heating source Hot Water Temperature value",
        "unique_id": "r290_heatpump_auxiliary_heating_source_hot_water_temperature_value",
        "address": 0x0072,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": UnitOfTemperature.CELSIUS,
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": "measurement",
        "precision": 1,
        "enabled_by_default": False,
    },
        {
        "name": "Auxiliary Heating source Heating Temperature value",
        "unique_id": "r290_heatpump_auxiliary_heating_source_heating_temperature_value",
        "address": 0x0073,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": UnitOfTemperature.CELSIUS,
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": "measurement",
        "precision": 1,
        "enabled_by_default": False,
    },
       {
        "name": "Buffer Tank Temperature T10",
        "unique_id": "r290_heatpump_buffer_tank_temperature_t10",
        "address": 0x0074,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": UnitOfTemperature.CELSIUS,
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": "measurement",
        "precision": 1,
        "enabled_by_default": False,
    },
        {
        "name": "Total Water Outlet Temperature",
        "unique_id": "r290_heatpump_total_water_outlet_temperature",
        "address": 0x0075,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": UnitOfTemperature.CELSIUS,
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": "measurement",
        "precision": 1,
        "enabled_by_default": False,
    },
        {
        "name": "Smart-Grid Status",
        "unique_id": "r290_heatpump_smart_grid_status",
        "address": 0x007A,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": "",
        "device_class": SensorDeviceClass.POWER,
        "state_class": "measurement",
        "precision": 1,
        "enabled_by_default": False,
    },
    {
        "name": "Zone 2 Mixing Valve Opening",
        "unique_id": "r290_heatpump_zone2_mixing_valve_opening",
        "address": 0x007B,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": "",
        "device_class": SensorDeviceClass.POWER,
        "state_class": "measurement",
        "precision": 1,
        "enabled_by_default": False,
    },
        {
        "name": "Zone 1 Mixing Temperature",
        "unique_id": "r290_heatpump_zone1_mixing_temperature",
        "address": 0x007C,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": UnitOfTemperature.CELSIUS,
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": "measurement",
        "precision": 1,
        "enabled_by_default": False,
    },
        {
        "name": "Zone 1 Mixing Valve Opening",
        "unique_id": "r290_heatpump_zone1_mixing_valve_opening",
        "address": 0x007D,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": "",
        "device_class": SensorDeviceClass.POWER,
        "state_class": "measurement",
        "precision": 1,
        "enabled_by_default": False,
    },
]





