from homeassistant.components.sensor import SensorDeviceClass
from homeassistant.components.number import NumberDeviceClass
from homeassistant.const import UnitOfTemperature

USER_PARAMETERS_SENSORS = [
    {
        "name": "Cooling set temperature",
        "unique_id": "r290_heatpump_cooling_set_temperature",
        "address": 0x0300,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": UnitOfTemperature.CELSIUS,
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": "measurement",
        "precision": 1,
    },
    {
        "name": "Heating set temperature",
        "unique_id": "r290_heatpump_heating_set_temperature",
        "address": 0x0301,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": UnitOfTemperature.CELSIUS,
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": "measurement",
        "precision": 1,
    },
    {
        "name": "Hot water set temperature",
        "unique_id": "r290_heatpump_hot_water_set_temperature",
        "address": 0x0302,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": UnitOfTemperature.CELSIUS,
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": "measurement",
        "precision": 1,
    },
    {
        "name": "Floor heating set temperature",
        "unique_id": "r290_heatpump_floor_heating_set_temperature",
        "address": 0x0303,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": UnitOfTemperature.CELSIUS,
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": "measurement",
        "precision": 1,
    },
    {
        "name": "Set mode",
        "unique_id": "r290_heatpump_set_mode",
        "address": 0x0304,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": None,
        "device_class": None,
        "state_class": "measurement",
        "precision": 0,
    },
    {
        "name": "On/Off",
        "unique_id": "r290_heatpump_on_off",
        "address": 0x0305,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": None,
        "device_class": None,
        "state_class": "measurement",
        "precision": 0,
    },
    {
        "name": "Indoor temperature set point",
        "unique_id": "r290_heatpump_indoor_temperature_set_point",
        "address": 0x0306,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": UnitOfTemperature.CELSIUS,
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": "measurement",
        "precision": 1,
    },
    {
        "name": "Frequency conversion mode",
        "unique_id": "r290_heatpump_frequency_conversion_mode",
        "address": 0x0307,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": None,
        "device_class": None,
        "state_class": "measurement",
        "precision": 0,
    },
    {
        "name": "Cooling curve setting",
        "unique_id": "r290_heatpump_cooling_curve_setting",
        "address": 0x0313,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": None,
        "device_class": None,
        "state_class": "measurement",
        "precision": 0,
    },
    {
        "name": "Heating curve setting",
        "unique_id": "r290_heatpump_heating_curve_setting",
        "address": 0x0314,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": None,
        "device_class": None,
        "state_class": "measurement",
        "precision": 0,
    },
    {
        "name": "Hot water curve setting",
        "unique_id": "r290_heatpump_hot_water_curve_setting",
        "address": 0x0315,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": None,
        "device_class": None,
        "state_class": "measurement",
        "precision": 0,
    },
    {
        "name": "Floor heating curve setting",
        "unique_id": "r290_heatpump_floor_heating_curve_setting",
        "address": 0x0316,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": None,
        "device_class": None,
        "state_class": "measurement",
        "precision": 0,
    },
]

# Writable Number entities for temperature setpoints
USER_PARAMETERS_WRITABLE_NUMBERS = [
    {
        "name": "Cooling set temperature",
        "unique_id": "r290_heatpump_cooling_set_temperature",
        "address": 0x0300,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": UnitOfTemperature.CELSIUS,
        "device_class": NumberDeviceClass.TEMPERATURE,
        "min_value": -20,
        "max_value": 80,
        "step": 1,
        "mode": "box",
        "precision": 1,
    },
    {
        "name": "Heating set temperature",
        "unique_id": "r290_heatpump_heating_set_temperature",
        "address": 0x0301,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": UnitOfTemperature.CELSIUS,
        "device_class": NumberDeviceClass.TEMPERATURE,
        "min_value": -20,
        "max_value": 80,
        "step": 1,
        "mode": "box",
        "precision": 1,
    },
    {
        "name": "Hot water set temperature",
        "unique_id": "r290_heatpump_hot_water_set_temperature",
        "address": 0x0302,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": UnitOfTemperature.CELSIUS,
        "device_class": NumberDeviceClass.TEMPERATURE,
        "min_value": -20,
        "max_value": 80,
        "step": 1,
        "mode": "box",
        "precision": 1,
    },
    {
        "name": "Floor heating set temperature",
        "unique_id": "r290_heatpump_floor_heating_set_temperature",
        "address": 0x0303,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": UnitOfTemperature.CELSIUS,
        "device_class": NumberDeviceClass.TEMPERATURE,
        "min_value": -20,
        "max_value": 80,
        "step": 1,
        "mode": "box",
        "precision": 1,
    },
    {
        "name": "Indoor temperature set point",
        "unique_id": "r290_heatpump_indoor_temperature_set_point",
        "address": 0x0306,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": UnitOfTemperature.CELSIUS,
        "device_class": NumberDeviceClass.TEMPERATURE,
        "min_value": -20,
        "max_value": 80,
        "step": 1,
        "mode": "box",
        "precision": 1,
    },
    {
        "name": "Water Zirculation Time",
        "unique_id": "r290_heatpump_water_zirculation_time",
        "address": 0x080F,
        "input_type": "holding",
        "data_type": "int16",
        "scale": 1,
        "unit": "min",
        "device_class": NumberDeviceClass.DURATION,
        "min_value": 1,
        "max_value": 30,
        "step": 1,
        "mode": "box",
        "precision": 0,
    },

]

# Optional: user-selectable parameters (exposed as select entities)
# Example entries (adjust addresses/options using your spreadsheet):
# USER_PARAMETERS_SELECTS = [
#     {
#         "name": "Operating mode",
#         "unique_id": "r290_heatpump_operating_mode",
#         "address": 0x0310,
#         "options": {
#             "Auto": 0,
#             "Heating": 1,
#             "Cooling": 2,
#             "DHW": 3,
#         },
#         "scan_interval": 30,
#     },
# ]
USER_PARAMETERS_SELECTS = [
    {
        "name": "Set mode",
        "unique_id": "r290_heatpump_set_mode",
        "address": 0x0304,
        "options": {
            "Cooling": 0,
            "Heating": 1,
            "Hot water": 2,
            "Floor heating": 3,
            "Hot water + cooling": 4,
            "Hot water + heating": 5,
            "Reserve": 6,
            "Hot water + floor heating": 7,
        },
        "scan_interval": 30,
    },
    {
        "name": "On/Off",
        "unique_id": "r290_heatpump_on_off",
        "address": 0x0305,
        "options": {
            "Power off": 0,
            "Power on": 1,
        },
        "scan_interval": 30,
    },
    {
        "name": "Frequency conversion mode",
        "unique_id": "r290_heatpump_frequency_conversion_mode",
        "address": 0x0307,
        "options": {
            "Standard mode": 0,
            "High power mode": 1,
            "Silent mode": 2,
        },
        "scan_interval": 30,
    },
    {
        "name": "Cooling curve setting",
        "unique_id": "r290_heatpump_cooling_curve_setting",
        "address": 0x0313,
        "options": {
            "Off": 0,
            "Curve 1": 1,
            "Curve 2": 2,
            "Curve 3": 3,
            "Curve 4": 4,
            "Curve 5": 5,
            "Curve 6": 6,
            "Curve 7": 7,
            "Curve 8": 8,
        },
        "scan_interval": 60,
    },
    {
        "name": "Heating curve setting",
        "unique_id": "r290_heatpump_heating_curve_setting",
        "address": 0x0314,
        "options": {
            "Off": 0,
            "Curve 1": 1,
            "Curve 2": 2,
            "Curve 3": 3,
            "Curve 4": 4,
            "Curve 5": 5,
            "Curve 6": 6,
            "Curve 7": 7,
            "Curve 8": 8,
        },
        "scan_interval": 60,
    },
    {
        "name": "Hot water curve setting",
        "unique_id": "r290_heatpump_hot_water_curve_setting",
        "address": 0x0315,
        "options": {
            "Off": 0,
            "Curve 1": 1,
            "Curve 2": 2,
            "Curve 3": 3,
            "Curve 4": 4,
        },
        "scan_interval": 60,
    },
    {
        "name": "Floor heating curve setting",
        "unique_id": "r290_heatpump_floor_heating_curve_setting",
        "address": 0x0316,
        "options": {
            "Off": 0,
            "Curve 1": 1,
            "Curve 2": 2,
            "Curve 3": 3,
            "Curve 4": 4,
            "Curve 5": 5,
            "Curve 6": 6,
            "Curve 7": 7,
            "Curve 8": 8,
        },
        "scan_interval": 60,
    },
]

USER_PARAMETERS_SWITCHES = [
    {
        "name": "Water Zirculation",
        "unique_id": "r290_heatpump_water_zirculation",
        "address": 0x080B,
        "input_type": "holding",
        "data_type": "int16",
        "on_value": 1,
        "off_value": 0,
        "duration_address": 0x080F,
        "duration_scale": 1,
        "default_duration_minutes": 5,
    },
]

